"""A fabricated end-to-end walkthrough of one auction, printed as text.

Committed output lives in ``docs/TACTICAL_WALKTHROUGH.md``. Every player here
is ``Fabricated####``; no real name and no projection row appears.

The ten things it is built to show are numbered in the output.
"""

from __future__ import annotations

import time
from dataclasses import replace
from typing import List

from ..auction.demo import DEMO_OWNERS
from ..auction.state import new_auction
from ..league import Position
from ..market.live import SaleObservation
from .bidders import assess_bidder, assess_room_bidders
from .board import BoardSettings, continue_shared_board
from .demo import build_tactical_demo, demo_sales
from .endgame import assess_endgame
from .maxbid import (TacticalCache, TacticalScenario, TacticalSettings,
                     evaluate_tactical)
from .recipients import enumerate_recipients

__all__ = ["walkthrough"]

_FAST = TacticalSettings(
    max_prices=4,
    completion=replace(TacticalSettings().completion, beam_width=32,
                       candidate_pool=30, proxy_candidates=32, finalists=2,
                       max_candidates=160),
    board=replace(BoardSettings(), pool_depth=110),
    max_recipients=2, proxy_reps=16)
_SCEN = (TacticalScenario("base", "base", "fabricated_base", is_base=True),)


def _p(out: List[str], *lines: str) -> None:
    out.extend(lines)


def walkthrough() -> str:
    out: List[str] = []
    _p(out, "# Fabricated tactical walkthrough", "",
       "Generated by `python -m ceauction.tactical.walkthrough`. Every player is",
       "`Fabricated####`; no real name, price or projection row appears here.",
       "All numbers are produced by formulas and describe nobody.", "")

    d = build_tactical_demo()
    cid = d.candidate().player_id
    key = d.key_for(cid)
    cache = TacticalCache()

    def tac(dd, **kw):
        return evaluate_tactical(dd.state, dd.cast, dd.costs, kw.pop("cid", cid),
                                 settings=_FAST, scenarios=_SCEN,
                                 market=dd.market, candidate_key=dd.key_for(cid),
                                 key_by_id=dd.key_by_id, **kw)

    # 1 -------------------------------------------------------------------
    opening = tac(d)
    _p(out, "## 1. Opening maximum, before any sale is recorded", "",
       "```", f"candidate                   player {cid} "
       f"({opening.endgame.position})",
       f"legal maximum               ${opening.legal_max}",
       f"financial-control threshold ${opening.financial_control_threshold}",
       f"robust tactical maximum     {opening.robust_tactical_max}",
       f"robust bracket              {opening.robust_bracket}",
       f"tested prices               {list(opening.tested_prices)}",
       f"mode                        {opening.mode} "
       f"({opening.result_kind})", "```", "",
       "The room state is the initial one and no sale has been fabricated into",
       "it. This is the *opening* number and it is a bracket, not a frontier.", "")

    # 2, 3 -----------------------------------------------------------------
    sales = demo_sales(d, 12)
    d2 = d.with_market(d.market.observe_all(sales))
    before = d.market.adjusted(key)
    after = d2.market.adjusted(key)
    _p(out, "## 2 & 3. Sales are recorded and the market prior updates", "",
       f"{len(sales)} fabricated sales: tight ends clearing at 0.45x the model,",
       "receivers near it, and one owner (Owner04) repeatedly paying up.", "",
       "```",
       f"market fingerprint   {d.market.fingerprint()} -> {d2.market.fingerprint()}",
       f"candidate band       {before.low}/{before.base}/{before.high}"
       f"  ->  {after.low}/{after.base}/{after.high}",
       f"anchor credibility   {before.anchor_credibility:.3f} -> "
       f"{after.anchor_credibility:.3f}",
       f"Owner04 evidence     {d2.market.buyer_levels['Owner04'].n} purchases "
       f"(threshold {d2.market.config.min_buyer_observations})",
       "```", "",
       "The displayed Sleeper anchor is unchanged and is never rewritten. What",
       "moved is the *expected clearing price* and how far the room is believed",
       "to follow the anchor. Two different quantities, two different fields.", "")

    o4 = assess_bidder(d2.state, "Owner04", cid, market=d2.market,
                       candidate_key=key, costs=d2.costs)
    o10 = assess_bidder(d2.state, "Owner10", cid, market=d2.market,
                        candidate_key=key, costs=d2.costs)
    _p(out, "Observed purchases distinguish one buyer, cautiously:", "", "```",
       f"Owner04  {o4.owner_observations} obs  willing "
       f"{o4.low}/{o4.base}/{o4.high}  buyer multiplier "
       f"{o4.buyer_multiplier:.3f}",
       f"Owner10  {o10.owner_observations} obs  willing "
       f"{o10.low}/{o10.base}/{o10.high}  buyer multiplier "
       f"{o10.buyer_multiplier}",
       "```", "",
       "Owner10 is below the evidence threshold and keeps the common prior. No",
       "personality was invented for either of them.", "")

    # 4 -------------------------------------------------------------------
    state = d2.state
    drained = "Owner06"
    spent: List[str] = []
    for spec in [s for s in state.available_specs
                 if s.player_id != cid][:2]:
        amount = state.owner(drained).max_bid
        if state.purchase_shortfall(spec.player_id, drained, amount) is None:
            state = state.apply_purchase(spec.player_id, drained, amount)
            spent.append(f"{drained} pays ${amount} for player {spec.player_id}")
    d3 = d2.with_state(state)
    eg3 = assess_endgame(d3.state, cid, current_price=None)
    _p(out, "## 4. A specific owner loses bidding capacity", "", "```")
    for line in spent:
        _p(out, f"  {line}")
    _p(out, f"  {drained} candidate legal max: "
       f"{assess_endgame(d2.state, cid).by_id[drained].candidate_legal_max} -> "
       f"{eg3.by_id[drained].candidate_legal_max}",
       f"  owners who can still compete: {len(eg3.competitors)}", "```", "")

    # 5 -------------------------------------------------------------------
    rs = enumerate_recipients(d3.state, cid, current_price=12, increment=1,
                              current_leader="Owner09", market=d3.market,
                              candidate_key=key, costs=d3.costs)
    live = tac(d3, current_price=12, increment=1, current_leader="Owner09")
    _p(out, "## 5. The same candidate to two different opponents", "",
       "Each named recipient is evaluated on its own branch. Nothing is",
       "averaged before the branches exist.", "", "```",
       f"  {'recipient':<34}{'price':>7}{'delta (proxy)':>16}  verdict")
    at_first = sorted({v.price for v in live.verdicts})[:1]
    for v in live.verdicts:
        if v.price in at_first:
            _p(out, f"  {v.recipient_label:<34}"
               f"{('-' if v.recipient_price is None else '$%d' % v.recipient_price):>7}"
               f"{v.delta:>16.5f}  {v.verdict}")
    _p(out, "```", "",
       "The deltas differ by recipient: the candidate strengthening one rival is",
       "not the same event as the candidate strengthening another, and the",
       "relative-to-league proxy sees that. In `--mode audited` the same",
       "structure runs through the real equity engine.", "")

    # 6 -------------------------------------------------------------------
    _p(out, "## 6. The live maximum differs from the opening maximum", "", "```",
       f"opening (no sales, no leader)   robust "
       f"{opening.robust_tactical_max}  bracket {opening.robust_bracket}  "
       f"legal max ${opening.legal_max}",
       f"live ($12 bid, leader Owner09)  robust "
       f"{live.robust_tactical_max}  bracket {live.robust_bracket}  "
       f"legal max ${live.legal_max}",
       f"cache keys                      {opening.cache_key} vs {live.cache_key}",
       "```", "",
       "Different room, different market state, different question, different",
       "cache key. Serving the opening number into the live moment is precisely",
       "the failure the fingerprint exists to prevent.", "")

    # 7 -------------------------------------------------------------------
    state = d3.state
    for o in list(state.owners):
        if o.owner_id == state.focus_owner_id:
            continue
        while state.owner(o.owner_id).max_bid > 4:
            owner = state.owner(o.owner_id)
            board = [s for s in state.available_specs
                     if s.player_id != cid
                     and state.purchase_shortfall(s.player_id, o.owner_id,
                                                  owner.max_bid) is None]
            if not board:
                break
            state = state.apply_purchase(board[-1].player_id, o.owner_id,
                                         owner.max_bid)
    d4 = d3.with_state(state)
    eg4 = assess_endgame(d4.state, cid, current_price=3, increment=1)
    _p(out, "## 7. An endgame in which one owner has financial control", "",
       "```",
       f"our legal maximum            ${eg4.our_legal_max}",
       f"highest rival legal maximum  ${eg4.highest_rival_legal_max}  "
       f"({eg4.top_rival})",
       f"financial-control threshold  ${eg4.financial_control_threshold}",
       f"we can guarantee winning     {eg4.we_can_guarantee_winning}",
       f"a rival can outbid us        "
       f"{eg4.rival_can_guarantee_outbidding_us or 'no'}",
       f"fall out at the next bid     {eg4.n_fall_out_at_next_bid}",
       f"$1 nomination uncontested    {eg4.dollar_nomination_uncontested}",
       f"league-wide $1 reserve       ${eg4.money_reserved_league_wide}",
       "```", "",
       "This is arithmetic. It says no rival *may* legally outbid us. It does",
       "not say buying is a good idea, and the tactical maximum is computed",
       "from equity branches rather than being set equal to the threshold.", "")

    # 8 -------------------------------------------------------------------
    fresh = new_auction(d.state.pool, DEMO_OWNERS, DEMO_OWNERS[0],
                        settings=d.state.settings)
    for pos, n in ((Position.QB, 9), (Position.RB, 3), (Position.WR, 2)):
        for spec in [s for s in fresh.available_specs
                     if Position(int(s.position)) is pos][:n]:
            fresh = fresh.apply_purchase(spec.player_id, "Owner02", 1,
                                         validate=False)
    qb = next(s for s in fresh.available_specs
              if Position(int(s.position)) is Position.QB)
    wr = next(s for s in fresh.available_specs
              if Position(int(s.position)) is Position.WR)
    eg_qb = assess_endgame(fresh, qb.player_id, current_price=1).by_id["Owner02"]
    eg_wr = assess_endgame(fresh, wr.player_id, current_price=1).by_id["Owner02"]
    _p(out, "## 8. Financial capacity exists; candidate legality does not", "",
       "Owner02 holds fourteen players: nine quarterbacks, three backs and two",
       "receivers. Every starting seat is covered except the third WR/TE one,",
       "so his last slot must hold a WR or a TE.", "", "```",
       f"  financial maximum bid        ${eg_qb.financial_max_bid}",
       f"  legal max on a QUARTERBACK   ${eg_qb.candidate_legal_max}   "
       f"({eg_qb.exclusion_reason})",
       f"  legal max on a RECEIVER      ${eg_wr.candidate_legal_max}",
       "```", "",
       "Same owner, same money, same moment. The difference is the candidate.", "")

    # 9 -------------------------------------------------------------------
    fresh2 = new_auction(d.state.pool, DEMO_OWNERS, DEMO_OWNERS[0],
                         settings=d.state.settings)
    qbs = [s for s in fresh2.available_specs
           if Position(int(s.position)) is Position.QB]
    for spec in qbs[:2]:
        fresh2 = fresh2.apply_purchase(spec.player_id, "Owner06", 1)
    d5 = d.with_state(fresh2)
    qb3 = qbs[2].player_id
    stacked = assess_bidder(d5.state, "Owner06", qb3, market=d5.market,
                            candidate_key=d5.key_for(qb3), costs=d5.costs)
    empty = assess_bidder(d5.state, "Owner07", qb3, market=d5.market,
                          candidate_key=d5.key_for(qb3), costs=d5.costs)
    _p(out, "## 9. A QB3 whose value is roster context, not a fixed premium", "",
       "```",
       f"  Owner06 (already holds two QBs)  fit '{stacked.roster_fit}'  "
       f"pursuit {stacked.pursuit_score:.3f}  willing "
       f"{stacked.low}/{stacked.base}/{stacked.high}",
       f"  Owner07 (holds none)             fit '{empty.roster_fit}'  "
       f"pursuit {empty.pursuit_score:.3f}  willing "
       f"{empty.low}/{empty.base}/{empty.high}",
       "```", "",
       "There is no quarterback premium and no quarterback maximum anywhere in",
       "the model. What differs is the seat the player would occupy. The stacked",
       "owner's interest is *reduced*, never forced to zero: the league has no",
       "positional quota and a third quarterback is a legal, sometimes sensible",
       "purchase.", "")

    # 10 ------------------------------------------------------------------
    t0 = time.perf_counter()
    imm = evaluate_tactical(d3.state, d3.cast, d3.costs, cid, settings=_FAST,
                            scenarios=_SCEN, market=d3.market,
                            candidate_key=key, key_by_id=d3.key_by_id,
                            current_price=12, increment=1,
                            current_leader="Owner09", cache=cache)
    imm_s = time.perf_counter() - t0
    t0 = time.perf_counter()
    hit = evaluate_tactical(d3.state, d3.cast, d3.costs, cid, settings=_FAST,
                            scenarios=_SCEN, market=d3.market,
                            candidate_key=key, key_by_id=d3.key_by_id,
                            current_price=12, increment=1,
                            current_leader="Owner09", cache=cache)
    hit_s = time.perf_counter() - t0
    aud_settings = replace(_FAST, mode="audited", completion=replace(
        _FAST.completion, selection_sims=400, evaluation_sims=400,
        rival_selection="proxy"))
    t0 = time.perf_counter()
    aud = evaluate_tactical(d3.state, d3.cast, d3.costs, cid,
                            settings=aud_settings, scenarios=_SCEN,
                            market=d3.market, candidate_key=key,
                            key_by_id=d3.key_by_id, current_price=12,
                            increment=1, current_leader="Owner09", prices=[13])
    aud_s = time.perf_counter() - t0
    v = aud.verdicts[0] if aud.verdicts else None
    _p(out, "## 10. Immediate versus audited", "", "```",
       f"immediate, cold        {imm_s:>7.2f}s   robust "
       f"{imm.robust_tactical_max}   basis: proxy, NO interval",
       f"immediate, cache hit   {hit_s * 1000:>7.1f}ms  from_cache="
       f"{hit.from_cache}",
       f"audited, ONE price     {aud_s:>7.2f}s   "
       f"{'' if v is None else 'delta %+.5f +/- %.5f (%s)' % (v.delta, 1.96 * (v.se or 0.0), v.verdict)}",
       "```", "",
       "The immediate answer is a proxy ordering with no confidence interval and",
       "is never labelled a championship-equity estimate. The audited answer is",
       "the real engine on matched seasons with an independent holdout sample,",
       "and it costs seconds per price per recipient -- which is why it belongs",
       "in `ce-lab tactical precompute`, between nominations, and never on the",
       "clock.", "")

    _p(out, "## What is still an assumption", "",
       "* Every willingness number is a **scenario range** under a named",
       "  assumption. Nothing is fitted; there is no historical auction for this",
       "  league to fit to.",
       "* Recipient weights are **stated scenario assumptions**, applied only",
       "  after each branch has been evaluated separately.",
       "* The clearing rule (second-highest willingness + one increment, capped)",
       "  is a documented auction **approximation**, not Sleeper's mechanism.",
       "* Opponent continuations use a named **proxy**, not championship equity.",
       "* A sparse ladder yields a **bracket**. Only `--refine` walks integers.", "")
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    print(walkthrough())
