"""``ce-lab auction …`` -- the auction layer's commands.

Kept out of ``cli.py`` because the auction layer is a package of its own and
its argument surface is large. Every command follows the same rules as the rest
of the CLI: validate inputs, exit non-zero on a usage error, never show a
traceback for something a user could reasonably get wrong, and say plainly
whether the inputs are fabricated and whether the answer is exact, heuristic or
unresolved.

No command may print an opening maximum, a recommended bid, or a predicted
clearing price. What they print is a CE reservation quantity under stated
assumptions.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from .completion import CompletionSettings, complete_roster, format_completion
from .costs import MissingCost
from .counterfactual import (PassDestination, compare_buy_vs_pass,
                             format_buy_pass)
from .demo import build_demo_auction
from .reservation import (ReservationCache, ScenarioSetup, estimate_runtime,
                          format_reservation, price_ladder, search_reservation)
from .state import AuctionError, AuctionRuleError, AuctionStateInvalid

__all__ = ["add_auction_parser", "dispatch"]

_FABRICATED_BANNER = (
    "INPUTS ARE FABRICATED. The player pool, the projections and the\n"
    "acquisition costs are all generated by a formula and describe no real\n"
    "player. Nothing printed below is a real value or a market price.")


def _settings(args) -> CompletionSettings:
    return CompletionSettings(
        beam_width=args.beam_width, candidate_pool=args.candidate_pool,
        finalists=args.finalists, ce_sims=args.sims, ce_seed=args.seed,
        proxy_seed=args.seed, max_runtime_s=args.max_seconds)


def _load(args):
    """Build the auction the command will run on.

    Only the fabricated demo exists as an input source today. A real auction
    state would arrive here as a file, and refusing clearly is better than
    inventing one: an auction state assembled from guesses would be a
    counterfactual pretending to be a room.
    """
    if getattr(args, "state", None):
        raise AuctionRuleError(
            "loading a real auction state from a file is not implemented; only "
            "--demo is available. Building one from guesses would be a "
            "counterfactual pretending to be a room.")
    demo = build_demo_auction()
    return demo


def _resolve_candidate(demo, args):
    if args.candidate is None:
        return demo.default_candidate().player_id
    if args.candidate not in demo.state.spec_by_id:
        raise AuctionRuleError(
            f"player {args.candidate} is not in this auction's pool")
    return args.candidate


def _pass_destination(args) -> PassDestination:
    if args.pass_to is None:
        return PassDestination.unavailable()
    if args.pass_price is None:
        raise AuctionRuleError(
            "--pass-to needs --pass-price: what the rival spends is money he no "
            "longer has, which is half of what the branch measures")
    return PassDestination.to_rival(args.pass_to, args.pass_price)


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_validate(args) -> int:
    demo = _load(args)
    problems = demo.state.problems()
    print(_FABRICATED_BANNER)
    print()
    print(f"auction state   {demo.state.fingerprint()}")
    print(f"owners          {len(demo.state.owners)}")
    print(f"pool            {len(demo.state.pool)} players, "
          f"{len(demo.state.available_ids)} available")
    print(f"complete        {demo.state.is_complete}")
    if problems:
        print(f"\nINVALID: {len(problems)} violation(s)")
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    print("\nVALID: every invariant holds.")
    if args.json_out:
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(
            json.dumps(demo.state.to_dict(), indent=2), encoding="utf-8")
        print(f"wrote {args.json_out}")
    return 0


def cmd_room(args) -> int:
    demo = _load(args)
    print(_FABRICATED_BANNER)
    print()
    print(demo.state.room_summary(next_bid=args.next_bid))
    return 0


def cmd_complete(args) -> int:
    demo = _load(args)
    settings = _settings(args)
    print(_FABRICATED_BANNER)
    print()
    try:
        result = complete_roster(demo.state, demo.cast, demo.costs,
                                 settings=settings, owner_id=args.owner,
                                 evaluate_ce=not args.no_ce)
    except MissingCost as exc:
        print(f"\ncost book is incomplete: {exc}", file=sys.stderr)
        return 2
    print(format_completion(result, cost_disclaimer=demo.costs.disclaimer()))
    if args.json_out:
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(json.dumps(result.to_dict(), indent=2),
                                       encoding="utf-8")
        print(f"\nwrote {args.json_out}")
    return 0 if result.best is not None else 1


def cmd_buy_pass(args) -> int:
    demo = _load(args)
    candidate = _resolve_candidate(demo, args)
    dest = _pass_destination(args)
    settings = _settings(args)
    print(_FABRICATED_BANNER)
    print()
    result = compare_buy_vs_pass(demo.state, demo.cast, demo.costs, candidate,
                                 args.price, dest, settings=settings,
                                 scenario_id=args.scenario)
    print(format_buy_pass(result, cost_disclaimer=demo.costs.disclaimer()))
    if args.json_out:
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(json.dumps(result.to_dict(), indent=2),
                                       encoding="utf-8")
        print(f"\nwrote {args.json_out}")
    return 0


def cmd_reservation(args) -> int:
    demo = _load(args)
    candidate = _resolve_candidate(demo, args)
    dest = _pass_destination(args)
    settings = _settings(args)

    scenario_ids = args.scenarios or ["fh-f000-s000-w1"]
    from ..realdata.scenarios import GRID_SIZE, ModelScenario
    for sid in scenario_ids:
        ModelScenario.from_id(sid)          # validates, raises on nonsense
    # The demo pool is fabricated and identical under every scenario -- there
    # is no contract to re-map -- so the scenario axis here exercises the API
    # rather than moving the players. Real specs would arrive as one state per
    # scenario, which is why ScenarioSetup carries a state at all.
    setups = [ScenarioSetup(sid, demo.state, demo.cast, demo.costs)
              for sid in scenario_ids]

    prices = (sorted(set(args.prices)) if args.prices
              else list(price_ladder(demo.state.focus.min_bid,
                                     demo.state.focus.max_bid, args.max_prices)))
    est = estimate_runtime(len(setups), len(prices), args.seconds_per_comparison)
    print(_FABRICATED_BANNER)
    print()
    print(f"estimated runtime: {est['comparisons']} comparison(s), "
          f"~{est['estimated_minutes']:.1f} minute(s) at "
          f"{args.seconds_per_comparison:.1f}s each")
    if len(scenario_ids) < GRID_SIZE:
        print(f"NOTE: {len(scenario_ids)} of {GRID_SIZE} scenarios. This is a "
              f"REDUCED grid, not the full cross-product.")
    if args.estimate_only:
        return 0
    print()

    cache = ReservationCache()
    result = search_reservation(setups, candidate, dest, prices=prices,
                                settings=settings, scenarios_available=GRID_SIZE,
                                cache=cache)
    print(format_reservation(result, cost_disclaimer=demo.costs.disclaimer()))
    print(f"\ncache: {cache.stats()}")
    if args.json_out:
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(json.dumps(result.to_dict(), indent=2),
                                       encoding="utf-8")
        print(f"wrote {args.json_out}")
    return 0


def cmd_slot_swap(args) -> int:
    """The 54-cell scenario-band experiment on the real contract."""
    from ..realdata.mapping import positional_fits_from_contract
    from ..realdata.scenarios import SCENARIO_GRID, ModelScenario
    from ..realdata.slot_swap import format_slot_swap, run_slot_swap

    path = Path(args.contract)
    if not path.exists():
        print(f"contract not found: {path}. Run `ce-lab ingest` first.",
              file=sys.stderr)
        return 2
    payload = json.loads(path.read_text(encoding="utf-8"))
    cv, miss = positional_fits_from_contract(payload)

    scenarios = SCENARIO_GRID
    if args.scenarios:
        scenarios = tuple(ModelScenario.from_id(s) for s in args.scenarios)
    if len(scenarios) < len(SCENARIO_GRID) and not args.allow_reduced:
        print(f"a committed slot-swap run uses all {len(SCENARIO_GRID)} "
              f"scenarios; got {len(scenarios)}. Pass --allow-reduced to run a "
              f"preview, which is labelled as reduced in the output.",
              file=sys.stderr)
        return 2

    exp = run_slot_swap(payload, positional_miss=miss, positional_cv=cv,
                        limit=args.limit, n_sims=args.sims, seed=args.seed,
                        scenarios=scenarios)
    print(format_slot_swap(exp, show_names=args.show_names))
    if args.json_out:
        Path(args.json_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.json_out).write_text(json.dumps(exp.summary(), indent=2),
                                       encoding="utf-8")
        print(f"\nwrote {args.json_out}")
    return 0


_COMMANDS = {
    "validate": cmd_validate,
    "room": cmd_room,
    "complete": cmd_complete,
    "buy-pass": cmd_buy_pass,
    "reservation": cmd_reservation,
    "slot-swap": cmd_slot_swap,
}


def dispatch(args) -> int:
    """Run the chosen sub-command, turning expected errors into exit codes."""
    fn = _COMMANDS.get(args.auction_command)
    if fn is None:
        print(f"unknown auction command {args.auction_command!r}", file=sys.stderr)
        return 2
    try:
        return fn(args)
    except AuctionStateInvalid as exc:
        print(f"\ninvalid auction state:", file=sys.stderr)
        for p in exc.problems:
            print(f"  - {p}", file=sys.stderr)
        return 2
    except (AuctionError, MissingCost, ValueError, KeyError) as exc:
        print(f"\n{type(exc).__name__.replace('Error', '')}: {exc}",
              file=sys.stderr)
        return 2


def add_auction_parser(sub) -> None:
    """Register ``ce-lab auction`` and its sub-commands."""
    p = sub.add_parser(
        "auction",
        help="auction room state, roster completion, buy/pass and CE "
             "reservation ranges")
    inner = p.add_subparsers(dest="auction_command", required=True)

    def common(sp, *, search=False, candidate=False):
        sp.add_argument("--demo", action="store_true", default=True,
                        help="use the fabricated demo auction (the only source "
                             "available; real states are not loadable yet)")
        sp.add_argument("--state", default=None,
                        help="a real auction-state file (NOT IMPLEMENTED; "
                             "refused rather than guessed)")
        sp.add_argument("--json-out", default=None,
                        help="write the full result as JSON")
        if search:
            sp.add_argument("--beam-width", type=int, default=120)
            sp.add_argument("--candidate-pool", type=int, default=45)
            sp.add_argument("--finalists", type=int, default=4)
            sp.add_argument("--sims", type=int, default=3000,
                            help="seasons per completion, matched across arms")
            sp.add_argument("--seed", type=int, default=20260904)
            sp.add_argument("--max-seconds", type=float, default=None,
                            help="runtime budget for one completion search")
        if candidate:
            sp.add_argument("--candidate", type=int, default=None,
                            help="player id; defaults to the best available")
            sp.add_argument("--pass-to", default=None,
                            help="owner who receives the candidate if we pass; "
                                 "omit for 'nobody gets him'")
            sp.add_argument("--pass-price", type=int, default=None,
                            help="what that owner pays; required with --pass-to")

    s = inner.add_parser("validate", help="check an auction state's invariants")
    common(s)

    s = inner.add_parser("room", help="print a sanitized room summary")
    common(s)
    s.add_argument("--next-bid", type=int, default=None,
                   help="also report who may legally bid this amount")

    s = inner.add_parser("complete",
                         help="solve a roster completion for one owner")
    common(s, search=True)
    s.add_argument("--owner", default=None,
                   help="owner to complete; defaults to the focus owner")
    s.add_argument("--no-ce", action="store_true",
                   help="rank by the proxy only and skip the CE simulation; "
                        "the output is then expected points, not equity")

    s = inner.add_parser("buy-pass",
                         help="compare buying a candidate with passing on him")
    common(s, search=True, candidate=True)
    s.add_argument("--price", type=int, required=True,
                   help="the price being considered, in whole dollars")
    s.add_argument("--scenario", default=None,
                   help="model scenario id, recorded in the output")

    s = inner.add_parser("reservation",
                         help="CE reservation-price range over a price ladder")
    common(s, search=True, candidate=True)
    s.add_argument("--prices", type=int, nargs="+", default=None,
                   help="explicit price ladder; default is an even ladder over "
                        "the legal range")
    s.add_argument("--max-prices", type=int, default=8)
    s.add_argument("--scenarios", nargs="+", default=None,
                   help="model scenario ids; a subset is reported as reduced")
    s.add_argument("--seconds-per-comparison", type=float, default=2.5,
                   help="used only for the runtime estimate printed first")
    s.add_argument("--estimate-only", action="store_true",
                   help="print the runtime estimate and stop")

    s = inner.add_parser(
        "slot-swap",
        help="the 54-cell scenario-band experiment on the real contract")
    s.add_argument("--contract", required=True,
                   help="normalized contract JSON from `ce-lab ingest`")
    s.add_argument("--limit", type=int, default=300)
    s.add_argument("--sims", type=int, default=16000)
    s.add_argument("--seed", type=int, default=20260904)
    s.add_argument("--scenarios", nargs="+", default=None)
    s.add_argument("--allow-reduced", action="store_true",
                   help="permit fewer than all 54 cells; the output says so")
    s.add_argument("--show-names", action="store_true",
                   help="print player names (LOCAL ONLY; committed output must "
                        "not carry them)")
    s.add_argument("--json-out", default=None)

    p.set_defaults(func=dispatch)
