"""``ce-lab market …`` -- anchors, priors, sales and room pressure.

Same rules as the rest of the CLI: validate inputs, exit non-zero on a usage
error, never show a traceback for something a user could reasonably get wrong,
and say plainly whether the inputs are fabricated or real.

No command may present a market price as our value or as a bid. What these print
is a **generic Sleeper anchor** and an **expected clearing price** under stated
scenarios; the championship-equity reservation range is a different quantity
computed elsewhere, and a tactical max bid is not built anywhere.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import List, Optional

from .anchors import AnchorError, load_sleeper_csv, match_anchors_to_contract
from .costbook import cost_book_from_market_state, cost_book_from_prior
from .demo import DEMO_SALES, build_demo_prior, demo_state
from .live import MarketState, SaleObservation, ShrinkageConfig
from .prior import MARKET_SCENARIOS, build_market_prior, format_prior_summary

__all__ = ["add_market_parser", "dispatch"]

_FABRICATED = (
    "INPUTS ARE FABRICATED. Anchors and prices are generated by a formula and\n"
    "describe no real player. Nothing below is a real market price.")

_REAL_BANNER = (
    "SOURCE: generic Sleeper 2026 '2qb' projected values. NOT this league's\n"
    "market, NOT championship-equity value, NOT a bid. Player-level output is\n"
    "written only to paths you name and must stay out of version control.")


class UsageError(Exception):
    """Something the caller can fix. Reported as a message, never a traceback."""


def _load_book(args):
    if not getattr(args, "csv", None):
        raise UsageError(
            "--csv is required for this command; there is no default path, "
            "because the anchor file lives outside version control")
    return load_sleeper_csv(args.csv, retrieved_at=getattr(args, "retrieved_at", None))


def _write_json(path: Optional[str], blob) -> None:
    if not path:
        return
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(blob, indent=2, default=str), encoding="utf-8")
    print(f"wrote {path}")


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


def cmd_ingest_sleeper(args) -> int:
    """Load, validate and summarise the anchor file. Aggregates only."""
    book = _load_book(args)
    print(_REAL_BANNER)
    print()
    s = book.summary()
    print(f"rows                 {s['rows']}")
    print(f"status               {s['status_counts']}")
    print(f"priced (rosterable)  {s['priced_players']}")
    print(f"priced raw total     ${s['priced_raw_total']}")
    print(f"priced display total ${s['priced_display_total']}")
    print(f"excluded from budget {s['excluded_from_budget']}  "
          f"(wrong position or inactive; the league cannot roster them)")
    print()
    print(f"  {'pos':<5}{'players':>9}{'raw $':>12}{'display $':>12}")
    for pos, v in s["positional"].items():
        print(f"  {pos:<5}{v['players']:>9}{v['raw_total']:>12}"
              f"{v['display_total']:>12}")
    print()
    print(f"anchor digest        {book.fingerprint()}")
    print(f"source sha256        {book.source_sha256[:16]}…")
    _write_json(args.json_out, s)
    return 0


def cmd_audit(args) -> int:
    """Join anchors to the real contract and report every way it fell short."""
    book = _load_book(args)
    path = Path(args.contract)
    if not path.exists():
        raise UsageError(f"contract not found: {path}. Run `ce-lab ingest` first.")
    payload = json.loads(path.read_text(encoding="utf-8"))
    matched, report = match_anchors_to_contract(book, payload.get("players", []))

    print(_REAL_BANNER)
    print()
    r = report.summary()
    for k in ("contract_players", "anchor_rows", "matched", "matched_priced",
              "match_rate", "unmatched_contract", "unmatched_anchor",
              "ambiguous", "duplicate_anchor_names", "position_conflicts",
              "anchor_inactive", "anchor_nonpositive",
              "anchor_ineligible_position"):
        print(f"  {k:<28} {r[k]}")
    print()
    print("  Counts only. Names of unmatched players are written to --json-out")
    print("  when you supply one, which must be an ignored local path.")
    if args.json_out:
        _write_json(args.json_out, {
            "summary": r,
            "unmatched_contract": report.unmatched_contract,
            "unmatched_anchor": report.unmatched_anchor,
            "ambiguous": report.ambiguous,
            "position_conflicts": report.position_conflicts,
        })
    return 0


def cmd_build_prior(args) -> int:
    """Anchor -> format adjustment -> budget reconciliation -> price band."""
    if args.demo:
        prior = build_demo_prior()
        print(_FABRICATED)
    else:
        book = _load_book(args)
        prior = build_market_prior(book)
        print(_REAL_BANNER)
    print()
    print(format_prior_summary(prior))
    _write_json(args.json_out, prior.summary())
    if args.players_out:
        if not args.demo:
            print("\nNOTE: player-level output contains identities. Write it only")
            print("      to an ignored local path.")
        _write_json(args.players_out,
                    [p.to_dict(include_identity=True) for p in prior.players])
    return 0


def _parse_sale(text: str, seq: int, prior) -> SaleObservation:
    """``key:position:price:buyer`` -- deliberately explicit, never guessed."""
    parts = text.split(":")
    if len(parts) != 4:
        raise UsageError(
            f"--sale must be KEY:POSITION:PRICE:BUYER, got {text!r}")
    key, pos, price, buyer = (p.strip() for p in parts)
    try:
        price_i = int(price)
    except ValueError:
        raise UsageError(f"sale price {price!r} is not a whole number") from None
    p = prior.by_key.get(key)
    return SaleObservation(
        player_key=key, position=pos.upper(), final_price=price_i, buyer=buyer,
        sequence=seq, prior_base=p.base_price if p and p.draftable else None,
        display_anchor=p.display_anchor if p else None)


def cmd_observe_sale(args) -> int:
    """Fold sales into the market state and show what moved."""
    prior = build_demo_prior() if args.demo else build_market_prior(_load_book(args))
    print(_FABRICATED if args.demo else _REAL_BANNER)
    print()
    state = MarketState(prior=prior, config=ShrinkageConfig(
        room=args.room_prior, position=args.position_prior,
        tier=args.tier_prior, buyer=args.buyer_prior))
    if args.state_in:
        state = MarketState.restore(prior, Path(args.state_in).read_text("utf-8"))

    sales: List[SaleObservation] = []
    if args.demo_sales:
        sales = DEMO_SALES(prior)
    for i, text in enumerate(args.sale or []):
        sales.append(_parse_sale(text, len(state.observations) + len(sales) + i,
                                 prior))
    if not sales:
        raise UsageError("supply at least one --sale, or --demo-sales")

    before = {pos: state.anchor_credibility(pos) for pos in prior.credibility}
    after_state = state.observe_all(sales)
    after = {pos: after_state.anchor_credibility(pos) for pos in prior.credibility}

    print(f"observations {len(state.observations)} -> {len(after_state.observations)}")
    print(f"market digest {state.fingerprint()} -> {after_state.fingerprint()}")
    print()
    head = f"  {'pos':<5}{'sales':>7}{'multiplier':>12}{'credibility before':>20}{'after':>9}"
    print(head)
    print("  " + "-" * (len(head) - 2))
    for pos in sorted(prior.credibility):
        lv = after_state.position_levels.get(pos)
        print(f"  {pos:<5}{(lv.n if lv else 0):>7}"
              f"{(lv.multiplier if lv else 1.0):>12.4f}"
              f"{before[pos]:>20.4f}{after[pos]:>9.4f}")
    print("  " + "-" * (len(head) - 2))
    room = after_state.room_effect
    print(f"  room-wide: {room.n} identifiable observation(s), "
          f"multiplier {room.multiplier:.4f}")
    print(f"  (a room-wide effect needs sales spanning more than one position; "
          f"{after_state.to_dict()['distinct_positions_observed']} seen)")
    print()
    print("  A final price is evidence about the CLEARING price. It does NOT")
    print("  reveal the winner's maximum, and it does NOT reveal any losing")
    print("  bidder's maximum beyond it being below the final price.")
    _write_json(args.json_out, after_state.to_dict())
    if args.state_out:
        Path(args.state_out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.state_out).write_text(after_state.serialize(), encoding="utf-8")
        print(f"wrote {args.state_out}")
    return 0


def cmd_player(args) -> int:
    """One player's anchor, prior and current expected clearing price."""
    prior = build_demo_prior() if args.demo else build_market_prior(_load_book(args))
    state = MarketState(prior=prior)
    if args.demo_sales:
        state = state.observe_all(DEMO_SALES(prior))
    if args.state_in:
        state = MarketState.restore(prior, Path(args.state_in).read_text("utf-8"))

    p = prior.by_key.get(args.key)
    if p is None:
        raise UsageError(
            f"no player with canonical key {args.key!r} in this board")
    print(_FABRICATED if args.demo else _REAL_BANNER)
    print()
    print(f"position            {p.position}")
    print(f"sleeper raw value   {p.raw_value}")
    print(f"sleeper display     "
          + (str(p.display_anchor) if p.display_anchor is not None
             else "UNPRICED (nonpositive; the UI rule was never observed)"))
    print(f"status              {p.status}")
    if not p.draftable:
        print(f"note                {p.notes}")
        _write_json(args.json_out, p.to_dict())
        return 0
    adj = state.adjusted(args.key, buyer=args.buyer)
    print(f"format adjusted     {p.format_adjusted:.2f}  "
          f"(credibility {p.credibility.weight:.3f})")
    print(f"prior band          ${p.low_price}-${p.high_price} (base ${p.base_price})")
    print(f"after {len(state.observations):>2} sale(s)    "
          f"${adj.low}-${adj.high} (base ${adj.base})")
    print(f"uncertainty         {adj.uncertainty:.3f}")
    print(f"anchor credibility  {adj.anchor_credibility:.4f}")
    print()
    print("  This is an EXPECTED CLEARING PRICE. It is not our championship-")
    print("  equity value, not a reservation price, and not a bid.")
    _write_json(args.json_out, {"prior": p.to_dict(), "adjusted": adj.to_dict()})
    return 0


def cmd_room_pressure(args) -> int:
    """Who can legally compete for a nominated player, and on what evidence."""
    from ..auction.demo import build_demo_auction
    from .pressure import assess_room_pressure, format_room_pressure

    if not args.demo:
        raise UsageError(
            "room-pressure runs on the fabricated demo auction only; loading a "
            "real auction state from a file is not implemented, and building "
            "one from guesses would be a counterfactual pretending to be a room")
    auction = build_demo_auction()
    prior = build_demo_prior()
    state = MarketState(prior=prior)
    if args.demo_sales:
        state = state.observe_all(DEMO_SALES(prior))

    candidate = (args.candidate if args.candidate is not None
                 else auction.default_candidate().player_id)
    if candidate not in auction.state.spec_by_id:
        raise UsageError(f"player {candidate} is not in this auction's pool")
    pressure = assess_room_pressure(auction.state, candidate, args.price,
                                    market=state, candidate_key=args.key)
    print(_FABRICATED)
    print()
    print(format_room_pressure(pressure))
    _write_json(args.json_out, pressure.to_dict())
    return 0


def cmd_cost_book(args) -> int:
    """Populate the acquisition-cost contract from a market scenario."""
    prior = build_demo_prior() if args.demo else build_market_prior(_load_book(args))
    state = MarketState(prior=prior)
    if args.demo_sales:
        state = state.observe_all(DEMO_SALES(prior))
    book = (cost_book_from_market_state(state, args.scenario,
                                        model_scenario=args.model_scenario)
            if state.observations else
            cost_book_from_prior(prior, args.scenario,
                                 model_scenario=args.model_scenario))
    print(_FABRICATED if args.demo else _REAL_BANNER)
    print()
    s = book.summary()
    print(f"market scenario     {args.scenario}")
    print(f"model scenario      {args.model_scenario or 'not stated'}")
    print(f"entries             {s['n_entries']}")
    print(f"cost fingerprint    {s['fingerprint']}")
    print(f"provenance level    {s['level']}")
    print(f"total assumed cost  ${s['total_assumed_cost']}")
    print(f"cost min/median/max ${s['cost_min']} / ${s['cost_median']} / ${s['cost_max']}")
    print()
    print(f"  {book.disclaimer()}")
    print()
    print("  Market cost and championship-equity value are separate axes. This")
    print("  book carries only the former.")
    _write_json(args.json_out, s)
    return 0


_COMMANDS = {
    "ingest-sleeper": cmd_ingest_sleeper,
    "audit": cmd_audit,
    "build-prior": cmd_build_prior,
    "observe-sale": cmd_observe_sale,
    "player": cmd_player,
    "room-pressure": cmd_room_pressure,
    "cost-book": cmd_cost_book,
}


def dispatch(args) -> int:
    fn = _COMMANDS.get(args.market_command)
    if fn is None:
        print(f"unknown market command {args.market_command!r}", file=sys.stderr)
        return 2
    try:
        return fn(args)
    except (UsageError, AnchorError, ValueError, KeyError) as exc:
        print(f"\n{type(exc).__name__.replace('Error', '')}: {exc}",
              file=sys.stderr)
        return 2


def add_market_parser(sub) -> None:
    p = sub.add_parser(
        "market",
        help="Sleeper anchors, expected clearing prices, live sale updates")
    inner = p.add_subparsers(dest="market_command", required=True)

    def common(sp, *, demo=True, csv=True, sales=False):
        if csv:
            sp.add_argument("--csv", default=None,
                            help="cleaned Sleeper CSV (an ignored local path)")
            sp.add_argument("--retrieved-at", default=None)
        if demo:
            sp.add_argument("--demo", action="store_true",
                            help="use fabricated anchors instead of a real file")
        if sales:
            sp.add_argument("--demo-sales", action="store_true",
                            help="apply the scripted fabricated sale sequence")
        sp.add_argument("--json-out", default=None,
                        help="write the full result as JSON")

    s = inner.add_parser("ingest-sleeper", help="load and summarise the anchors")
    common(s, demo=False)

    s = inner.add_parser("audit", help="join anchors to the real contract")
    common(s, demo=False)
    s.add_argument("--contract", required=True,
                   help="normalized contract JSON from `ce-lab ingest`")

    s = inner.add_parser("build-prior", help="expected clearing-price prior")
    common(s)
    s.add_argument("--players-out", default=None,
                   help="player-level output; LOCAL ONLY, must be ignored")

    s = inner.add_parser("observe-sale", help="fold sales into the market state")
    common(s, sales=True)
    s.add_argument("--sale", action="append",
                   help="KEY:POSITION:PRICE:BUYER; repeatable")
    s.add_argument("--state-in", default=None)
    s.add_argument("--state-out", default=None)
    s.add_argument("--room-prior", type=float, default=10.0)
    s.add_argument("--position-prior", type=float, default=5.0)
    s.add_argument("--tier-prior", type=float, default=6.0)
    s.add_argument("--buyer-prior", type=float, default=8.0)

    s = inner.add_parser("player", help="one player's anchor and price band")
    common(s, sales=True)
    s.add_argument("--key", required=True, help="canonical player key")
    s.add_argument("--buyer", default=None,
                   help="apply this owner's learned tendency, if he has enough")
    s.add_argument("--state-in", default=None)

    s = inner.add_parser("room-pressure",
                         help="who may legally compete for a nominated player")
    common(s, csv=False, sales=True)
    s.add_argument("--candidate", type=int, default=None)
    s.add_argument("--price", type=int, required=True)
    s.add_argument("--key", default=None,
                   help="canonical key, to attach an expected clearing price")

    s = inner.add_parser("cost-book",
                         help="populate the acquisition-cost contract")
    common(s, sales=True)
    s.add_argument("--scenario", default="base", choices=["low", "base", "high"])
    s.add_argument("--model-scenario", default=None,
                   help="performance/CE scenario id, recorded alongside")

    p.set_defaults(func=dispatch)
